defaults: &defaults
  salt: 'comapp-web'
  google:
    maps:
      key: AIzaSyCEJlD2gNMaGx3o0CFvLwfLixs0iGK192Q
development_and_test: &development_and_test
  <<: *defaults
development:
  <<: *development_and_test
test: &test
  <<: *development_and_test
production:
  <<: *defaults
  google:
    maps:
      key: '<%= ENV['COMAPP_GOOGLE_MAPS_KEY'] %>'
